config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'searches/search'
  end
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  scope module: 'public' do
    root 'homes#top'
    get 'about', to: 'homes#about'
    get 'searches/search'
    scope 'genres/:genre_id' do
      resources :games, only: %i[create show edit update destroy] do
        resources :game_comments, only: %i[create destroy]
        resource :favorites, only: %i[create destroy]
      end
    end

    resources :genres, only: %i[index show]
    resources :users, only: %i[index show edit update] do
      resource :relationships, only: %i[create destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      put '/users/:id/hide' => 'users#hide', as: 'users_hide'
    end
    post 'games/:id' => 'games#show'

    resources :contacts, only: %i[new create]
    post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
    post 'contacts/back', to: 'contacts#back', as: 'back'
    get 'done', to: 'contacts#done', as: 'done'
  end

  namespace :admin do
    root 'homes#top'
    resources :genres, only: %i[index create edit update destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :genre, optional: true

  has_many :game_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/game_comment.rb
class GameComment < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :comment, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :games

  attachment :profile_image, destroy: false
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games, dependent: :destroy
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :reverce_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :reverce_of_relationships, source: :follower
  has_many :game_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def active_for_authentication?
    super &&
      !!(is_deleted == false)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  attachment :profile_image
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top; end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="fixed-bottom mt-3">
    <div class='container bg-white'>
      <div class='row border-top py-2'>
        <div class='mx-auto justify-content-center'>
          <%= link_to "お問い合わせはこちらから", new_contact_path, class: "text-dark" %>
          <p>CopyRight KarzLightyear</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container bg-white">
    <div class="game-header py-3">
      <div class="row flex-nowarp justify-content-between align-items-center border-bottom">
        <div class="col-12 text-center m-2">
          <a class="game-header-logo" href="/"><%= image_tag "gamefans-logo.png" %></a>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg navbar-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container bg-white">
      <div class="row collapse navbar-collapse" id="navbarNavDropdown">
        <div class="collapse navbar-collapse border-bottom">
          <ul class="col-4 navbar-nav justify-content-start">
            <p class="nav-link text-success">
              <% if user_signed_in? %>
              ようこそ、<%= current_user.name %>さん！
              <% end %>
            </p>
          </ul>
          <ul class="col-4 navbar-nav justify-content-center">
            <% if user_signed_in? %>
              <!--カスタマーがログインしている時-->
              <li><%= link_to "Mypage", user_path(current_user), class: "fas fa-house-user nav-link text-success" %></li>
              <li><%= link_to "Games", genres_path, class: "fas fa-gamepad nav-link text-success" %></li>
              <li><%= link_to "Users", users_path, class: "fas fa-user nav-link text-success" %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-success" %></li>

            <% elsif admin_signed_in? %>
              <!--管理者がログインしている時-->
              <li><%= link_to "titles", admin_genres_path, class: "fas fa-plus nav-link text-success" %></li>
              <li><%#= link_to "", , class: "" %></li>
              <li><%#= link_to "", , class: "" %></li>
              <li><%#= link_to "", , class: "" %></li>
              <li><%= link_to "Logout", destroy_admin_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-success" %></li>

            <% else %>
              <!--ログインしていない時-->
              <li><%= link_to "Home", root_path, class: 'fas fa-home nav-link text-success' %></li>
              <li><%= link_to "About", about_path, class: 'fas fa-link nav-link text-success' %></li>
              <li><%= link_to "Signup", new_user_registration_path, class: 'fas fa-user-plus nav-link text-success' %></li>
              <li><%= link_to "Login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-success' %></li>
            <% end %>
          </ul>
          <ul class="col-4 navbar-nav justify-content-end">
            <%= render 'public/searches/search_box' %>
          </ul>
        </div>
      </div>
    </div>
  </nav>


</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamefans</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/a334d13857.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>

    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

  </head>
  
  <header>
    <%= render 'layouts/header' %>
  </header>

  <body class='mb-5'>
    <%= yield %>
  </body>
  
  <footer>
    <%= render 'layouts/footer' %>
  </footer>
</html>